name: 🏁 Sprint Planning
description: Set up a new sprint with goals and metrics
title: "[SPRINT]: 25-Q1 JFM - 1 (YYYY-MM-DD to YYYY-MM-DD)"
labels: ["sprint", "planning"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## 🏁 Sprint Planning
        Define sprint goals, scope, and success metrics.

  - type: input
    id: sprint-name
    attributes:
      label: 🗓️ Sprint Name
      description: Name of the sprint
      placeholder: "25-Q1 JFM - 1"
    validations:
      required: false

  - type: input
    id: duration
    attributes:
      label: 📆 Sprint Duration
      description: Start and end dates
      placeholder: "Mar 10 - Mar 24, 2025"
    validations:
      required: false

  - type: textarea
    id: sprint-goals
    attributes:
      label: 🎯 Sprint Goals
      description: 1-3 clear objectives for this sprint
      placeholder: |
        1. 🚀 Complete user authentication flow
        2. 🚀 Improve API response time by 20%
        3. 🚀 Release v1.2 to staging
    validations:
      required: false

  - type: textarea
    id: sprint-scope
    attributes:
      label: 📋 Sprint Scope
      description: User stories committed for this sprint with points
      placeholder: |
        - [ ] #123 User Login (S - 5 points)
        - [ ] #124 Password Reset (M - 8 points)
        - [ ] #125 API Optimization (M - 8 points)
    validations:
      required: false

  - type: input
    id: capacity
    attributes:
      label: 📊 Team Capacity
      description: Total team capacity for this sprint
      placeholder: "50 points"
    validations:
      required: false

  - type: input
    id: velocity
    attributes:
      label: 📈 Previous Velocity
      description: Completed points from last sprint
      placeholder: "45 points"
    validations:
      required: false

  - type: textarea
    id: risks
    attributes:
      label: ⚠️ Risks and Dependencies
      description: Known risks that might impact sprint delivery
      placeholder: |
        - New team member onboarding
        - External dependency on API changes
        - Upcoming holidays may reduce capacity
    validations:
      required: false

  - type: textarea
    id: planning-insights
    attributes:
      label: 🔍 Sprint Planning Insights
      description: Notes from planning session
      placeholder: |
        - Key discussions
        - Trade-offs made
        - Special considerations
    validations:
      required: false

  - type: textarea
    id: success-criteria
    attributes:
      label: 🏆 Success Criteria
      description: How will we measure success for this sprint?
      placeholder: |
        - All committed stories completed
        - Zero regression bugs
        - Specific metric improvements
        - Demo-ready by sprint end
    validations:
      required: false

  - type: textarea
    id: team-availability
    attributes:
      label: 👥 Team Availability
      description: Any planned time off or reduced capacity
      placeholder: |
        - Team member 1: PTO on Mar 15
        - Team member 2: 50% capacity, working on support
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ---
        👨‍💻 For assistance with this template, contact @ramanaditya